version: "3.4"
services:
  squid:
    image: sameersbn/squid:3.5.27-2
#   image: sameersbn/squid:latest
    container_name: squid
    hostname: squid
    volumes:
     - ./config/squid.conf:/etc/squid/squid.conf
    ports:
     - "localhost:3128:3128"
